// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/26/2026, 11:41:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/marquis/curatewithng/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/plugins/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/website/composables/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/website/utils/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/website/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;